### ISSUE TITLE
Multiple Tag Managers

### ISSUE THREAD

**Issue by dancwilliams** [sergeymaysak/wirelesstagpy#1]
Hello,

First, thanks for putting this together!  Very nice!

I have two tag managers under my account.  When I am testing your library I am only able to load sensor data from the last tag manager I visited through the web console.  I doesn't just list all devices from both tag managers under the same account.

Any ideas?  I willing to provide more details when/if needed.

Again...thanks!

**Comment by sergeymaysak** [comment]
Hi Dan,

Well, true. To the moment this is "known limitation" of my implementation - I do support single tag manager only. I have two managers already as well. And share your pain. I started working on the issue some time ago, but cannot say when it will be finished (just out of time for this at the moment)...

Thanks,
Sergey

**Comment by dancwilliams** [comment]
No problem!  Thank you for the quick reply.

This is the first I have really looked into the WirelessTag API.  May have to spend some cycles on it the next couple of weeks. 

In the mean time I will just have to decide which sensors I care more about :-)

Thanks!

**Comment by dancwilliams** [comment]
@sergeymaysak 

I created pull request #2 to address this.  Hope this helps!

Dan

**Comment by dancwilliams** [comment]
Belay my last.  Ran out of time.

**Comment by sergeymaysak** [comment]
@dancwilliams 
Please check [multiple_tag_managers branch](https://github.com/sergeymaysak/wirelesstagpy/tree/multiple_tag_managers) where I implemented support for multiple tag managers.
Hope this what you are looking for )
If no issues arise -  I will merge to master and publish to pypi version 0.4.0 with these changes...

**Comment by dancwilliams** [comment]
@sergeymaysak 

Tests out great in my setup.  I really appreciate you taking the time to put this together.  This is really going to change the way I can do some things around the house!
