### ISSUE TITLE
wirelesstagpy 0.4.0 has requirement colorlog==3.0.1, but you'll have colorlog 4.0.2 which is incompatible.

### ISSUE THREAD

**Issue by decv86** [sergeymaysak/wirelesstagpy#7]
Hi!

Error subject, its support?

*wirelesstagpy 0.4.0 has requirement colorlog==3.0.1, but you'll have colorlog 4.0.2 which is incompatible.

**Comment by MartinHjelmare** [comment]
- This library supports an integration in Home Assistant.
- The upcoming pip resolver will be more strict in resolving package version conflicts:
http://pyfound.blogspot.com/2020/03/new-pip-resolver-to-roll-out-this-year.html#what-will-change
- To avoid future issues it would be good if this library would change its pinning to allow any higher version and just set a minimum version.

Thanks for your support of Home Assistant!

**Comment by sergeymaysak** [comment]
Resolved in just released v. 0.4.1 (I removed dependency on colorlog entirely). PR in HA: https://github.com/home-assistant/core/pull/38387

Thanks for pointing on the issue! )

**Comment by MartinHjelmare** [comment]
Awesome, thanks!

If you have time, please also do a github release or tag for 4.0.1, to help users track changes between versions. :+1:

**Comment by sergeymaysak** [comment]
Right! ) Just made release/tag for 0.4.1. Thanks!
